name: Notify over MQTT when file changes

on:
  push:
    branches:
      - main
    paths:
      - "mini-tft-esp32s3.bin"
  workflow_dispatch:

jobs:
  mqtt-notify:
    runs-on: [self-hosted, proxmox]  # label you gave the runner

