name: Notify over MQTT when new bin file release is published

on:
  release:
    types: [published]   # triggers when a release is published
  workflow_dispatch:

jobs:
  mqtt-notify:
    runs-on: [self-hosted, proxmox]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure release tag is semver
        run: |
          tag="${{ github.event.release.tag_name }}"
          echo "Release tag: $tag"
          if ! [[ "$tag" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
            echo "Tag '$tag' is not a semver (expected like v1.2.3). Aborting."
            exit 1
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install mqtt package
        run: npm install mqtt --no-audit --no-fund

      - name: Get release tag
        id: get_tag
        run: |
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Debug connectivity (optional)
        run: |
          echo "curl debug (from self-hosted runner):"
          curl -I -sS https://$(echo ${{ secrets.MQTT_HOST }} | sed -E 's#^wss://##; s#/.*$##')/mqtt || true

      - name: Run MQTT publisher
        env:
          MQTT_HOST: ${{ secrets.MQTT_HOST }}
          MQTT_PATH: ${{ secrets.MQTT_PATH }}
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          RELEASE_TAG: ${{ steps.get_tag.outputs.tag }}
          MQTT_ATTEMPTS: 4
          MQTT_RETRY_DELAY_MS: 3000
          MQTT_CONNECT_TIMEOUT_MS: 15000
        run: |
          node .github/workflows/send-mqtt.js
